FisioWebFront/Controllers/InformacionController.cs
using FisioWebFront.Class;
using FisioWebFront.Entities;
using FisioWebFront.Models;
using Microsoft.AspNetCore.Mvc;

namespace FisioWebFront.Controllers
{
    public class InformacionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private readonly IConfiguration _config;
        InformacionModel model = new InformacionModel();

        public InformacionController(IConfiguration config)
        {
            _config = config;
        }

        [HttpGet]
        public ActionResult VerSobreNosotros()
        {
            return View();
        }


		[HttpGet]
		public ActionResult VerContacto()
		{
			return View();
		}


		[HttpPost]
		public ActionResult VerContacto( CorreoOBJ correoUsuario)
		{
			EnviarCorreo enviarCorreo = new EnviarCorreo();
            enviarCorreo.ConsultaRealizada(correoUsuario);
			return View();
		}


 

	}

}

FisioWebFront/Views/Informacion/VerContacto.cshtml
@model FisioWebFront.Entities.CorreoOBJ
@{
	ViewBag.Title = "VerContacto";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
	<![endif]-->

	<div class="preloader">
		<div class="preloader_image"></div>
	</div>


	<!-- search modal -->
	<div class="modal" tabindex="-1" role="dialog" aria-labelledpor="search_modal" id="search_modal">
		<div class="widget widget_search">
			<form method="get" class="searchform form-inline" action="https://html.modernwebtemplates.com/">
				<div class="form-group">
					<input type="text" value="" name="search" class="form-control" placeholder="Search keyword" id="modal-search-input">
				</div>
				<button type="submit" class="theme_button">Search</button>
			</form>
		</div>
	</div>

	<!-- wrappers for visual page editor and boxed version of template -->
	<div id="canvas">
		<div id="box_wrapper">
			<section class="page_breadcrumbs ls ms columns_margin_0">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 ">
							<ol class="breadcrumb">
								<li>
									<a href="index.html">
										Inicio
									</a>
								</li>

								<li class="active">Contacto</li>
								 
							</ol>
						</div>
					</div>
				</div>
			</section>
			<section class="ls section_padding_top_65 section_padding_bottom_100">
				<div class="container">
										@using (Html.BeginForm("VerContacto", "Informacion", FormMethod.Post))
					{
						<div class="row">

						<div class="col-md-8 to_animate" data-animation="scaleAppear">

							<h3 class="section_header small bottommargin_30">
								Enviar
								<strong>Correo</strong>
							</h3>

							<form class="contact-form row columns_padding_5" method="post" action="https://html.modernwebtemplates.com/">

								<div class="col-sm-6">
									<div class="contact-form-name">
										<label for="name">
											Nombre Completo
											<span class="required">*</span>
										</label>

										 @Html.TextBoxFor(model => model.nombre, new { @type="text", @required="required",
										@size="30", @value="" ,@name="name" ,@id="name", @class="form-control", @placeholder="Nombre"})
									</div>
								</div>
								<div class="col-sm-6">
									<div class="contact-form-subject">
										<label for="subject">
											Asunto
											<span class="required">*</span>
										</label>
											@Html.TextBoxFor(model => model.subject, new {@type="text", @required="required", @size="30",
											@value="", @name="", @id="subject", @class="form-control", placeholder="Asunto"})
									</div>
								</div>
								<div class="col-sm-6">
									<div class="contact-form-phone">
										<label for="phone">
											Telefono/Celular
											<span class="required">*</span>
										</label>
											@Html.TextBoxFor(model => model.telefono, new {@type="text", @required="required", @size="30",
										@value="", @name="", @id="telefono", @class="form-control", placeholder="Telefono",
										@pattern =@"^([^\\S]|(?!e))\d{8,12}([^\\S]|$)$"})
										</div>
								</div>
								<div class="col-sm-6">
									<div class="contact-form-email">
										<label for="email">
											Email
											<span class="required">*</span>
										</label>
											@Html.TextBoxFor(model => model.correo_to, new {@type="text", @required="required", @size="30",
										@value="", @name="", @id="email", @class="form-control", placeholder="Email",
										@pattern=@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"	})
										</div>
								</div>
								<div class="col-sm-12">

									<div class="contact-form-message">
										<label for="message">Mensaje</label>
											@Html.TextAreaFor(model => model.contenido, new { @required="required" ,@rows="6" ,@cols="45" ,@name="message", @id="message", @class="form-control", @placeholder="Mensaje"})
									</div>
								</div>

								<div class="col-sm-12">

									<div class="contact-form-submit topmargin_30">
											<button onsubmit="MostrarAlerta()" on type="submit" id="contact_form_submit" name="contact_submit" class="theme_button color1">Enviar Mensaje</button>
									</div>
								</div>


							</form>
						</div>

						<div class="col-md-4 to_animate" data-animation="scaleAppear">

							<h3 class="section_header small bottommargin_30">
								Informacion de
								<strong>Contacto</strong>
							</h3>

							<div>
								<div class="media contact_teaser">
									<div class="media-left media-middle fontsize_20">
										<i class="fa fa-map-marker"></i>
									</div>
									<div class="media-body media-middle lightfont">
										<span class="small-text">Ubicacion</span>
										<p class="fontsize_18 highlight semibold">Curridabat, San José</p>
									</div>
								</div>

								<div class="media contact_teaser">
									<div class="media-left media-middle fontsize_20">
										<i class="fa fa-clock-o"></i>
									</div>
									<div class="media-body media-middle lightfont">
										<span class="small-text">Telefono de Contacto</span>
										<p class="fontsize_18 highlight semibold">(506) 2271 0789</p>
									</div>
								</div>

								<div class="media contact_teaser">
									<div class="media-left media-middle fontsize_20">
										<i class="fa fa-pencil"></i>
									</div>
									<div class="media-body media-middle lightfont">
										<span class="small-text">Nuestro Email</span>
										<p class="fontsize_18 highlight semibold">info@fisiovetcr.com</p>
									</div>
								</div>



								<div class="media contact_teaser">
									<div class="media-left media-middle fontsize_20">
										<span class="greylinks">
											<a href="https://www.facebook.com/fisiovetcr" class="social-icon soc-facebook"></a>
										</span>
									</div>
									<div class="media-body media-middle lightfont">
										<a href="https://www.facebook.com/fisiovetcr" class="fontsize_18 highlight semibold">Facebook</a>
									</div>
								</div>


								<div class="media contact_teaser">
									<div class="media-left media-middle fontsize_20">
										<span class="greylinks">
											<a href="https://www.instagram.com/fisiovetcr/" class="social-icon soc-instagram"></a>
										</span>
									</div>
									<div class="media-body media-middle lightfont">
										<a href="https://www.instagram.com/fisiovetcr/" class="fontsize_18 highlight semibold">Instagram</a>
									</div>
								</div>



							</div>

						</div>

					</div>
					}
				</div>
			</section>

		</div>
		<!-- eof #box_wrapper -->
	</div>
	<!-- eof #canvas -->
	<script src="~/fluffypaw/js/compressed.js"></script>
	<script src="~/fluffypaw/js/main.js"></script>
	<script src="~/fluffypaw/js/switcher.js"></script>
	<script src="~/js/sweetalert2.all.min.js"></script>

	<script>
		function MostrarAlerta() {
			Swal.fire({
				position: 'top-end',
				icon: 'success',
				title: 'Consulta Enviada',
				showConfirmButton: false,
				timer: 1500
			})
		}
	</script>

	</script>


</body>

FisioWebFront/Views/Informacion/VerSobreNosotros.cshtml
@*@model FisioWebFront.Entities.UsuarioObj*@
@{
    ViewBag.Title = "CambiarClave";
Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
	<![endif]-->

	<div class="preloader">
		<div class="preloader_image"></div>
	</div>


	<!-- search modal -->
	<div class="modal" tabindex="-1" role="dialog" aria-labelledpor="search_modal" id="search_modal">
		<div class="widget widget_search">
			<form method="get" class="searchform form-inline" action="https://html.modernwebtemplates.com/">
				<div class="form-group">
					<input type="text" value="" name="search" class="form-control" placeholder="Search keyword" id="modal-search-input">
				</div>
				<button type="submit" class="theme_button">Search</button>
			</form>
		</div>
	</div>
 
	<div id="canvas">
		<div id="box_wrapper">



			<section class="page_breadcrumbs ls ms columns_margin_0">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 ">
							<ol class="breadcrumb">
								<li>
									<a href="index.html">
										Inicio
									</a>
								</li>
								<li class="active"> Sobre nosotros</li>
							</ol>
						</div>
					</div>
				</div>
			</section>

			<section class="ls section_padding_110">
				<div class="container">
					<div class="row">

						<div class="col-sm-10 col-sm-push-1">

							<div class="with_border">

								<div class="entry-thumbnail item-media">
									<img src="~/fluffypaw/images/FV_img02.jpg" alt="">
								</div>

								<div class="with_padding">
									<article>

										<header class="entry-header">

											<span class="pull-left date small-text type2 highlight">
												<time datetime="2016-08-01T15:05:23+00:00" class="entry-date">
													Diciembre, 2021
												</time>
											</span>

											<span class="greylinks pull-right small-text type2">
												<a href="#">Personal FisioVet</a>
											</span>

											<div class="clearfix"></div>

											<h4 class="entry-title semibold bottommargin_20">
												Conozca más acerca de nuestra clínica y su personal
											</h4>

										</header>
										<!-- .entry-header -->

										<div class="entry-content">
											<p>
												Este mes de diciembre, nuestra clínica se encuentra cumpliendo 6 años 🎉	<br>
												Durante estos 6 años hemos pasado momentos de todo tipo, pero gracias a todas las personas que creen y ven resultados en nuestro trabajo seguimos creciendo para poder ofrecerles siempre la mejor calidad en los servicios que brindamos, este año estuvo plasmado de grandes cosas, tuvimos una ampliación de nuestra clínica, incluimos el servicio de rayos x para facilitar y agilizar los diagnósticos, nuestro personal creció, teniendo por tiempo completo al dr.salmeron  en nuestra clínica, recibimos varias capacitaciones que involucraron al crecimiento de nuestro personal, incluimos los productos Walkin Pets en nuestra tienda, los cuales ayudan a mascotas con discapacidades a tener una mejor calidad de vida, entre muchas otras cosas buenas que nos pasaron este año.
												Muchas gracias a todos ustedes por ser parte de este año de éxitos y estamos seguros de que este siguiente año seguiremos creciendo para ofrecerles siempre el mejor servicio en terapia y rehabilitación de mascotas del país. 🐶🐱
											</p>

											<blockquote class="text-center">
												<p class="grey">"Falta quote"</p>

												<div class="item-meta topmargin_30">
													<h5>
														Michelle
														<strong>Rodriguez</strong>
													</h5>
													<p class="small-text highlight">Propietaria de la clínica</p>
												</div>
											</blockquote>

											<p>
												En nuestra clínica Fisiovet contamos con gran variedad en alimentos para perritos y gatitos.🐶🐱
												Alimentos medicados y escogidos de las mejores marcas para que le brindes a tu mascota una excelente alimentación. 🦴
												Entre ellos están alimentos reguladores de peso, alimentos para diabéticos, para mascotas ancianas, mordida pequeña, renal, hipoalergénico, entre otros. Contamos con marcas como Balance, Purina, Nutri Source, VetLife, Proplan, Hill´s.
												<br>
												Además, nuestros servicios se han venido ampliando:
											</p>
											<ul class="list2">

												<li>Termoterapia</li>
												<li>Magento</li>
												<li>Láser</li>
												<li>Ultrasonido</li>
												<li>Electroestimulación</li>
												<li>Electroacupuntura</li>
												<li>Masajes</li>
												<li>Caminadora de agua</li>
												<li>Piscina</li>

											</ul>
											<p class="topmargin_30">
												<img class="alignleft" alt="" src="images/FV_img01.jpg">
											</p>
											<p>
												Nuestra clínica ha cambiado mucho desde el 2016.
												Actualmente nuestras instalaciones crecieron para el bien de todos nuestros pacientes.
												Hoy en día contamos con una clínica especializada en terapia y rehabilitación para mascotas 🐶, la cual cuenta con tres consultorios, tienda de productos veterinarios, recepción y diferentes espacios para que nuestros pacientes tengan un servicio de calidad
											</p>

										</div>
										<!-- .entry-content -->


										<br>	<br>	<br>	<br>	<br>	<br>	<br>
										<h4 class="entry-title semibold bottommargin_20">
											Nuestro personal
										</h4>
										<div class="row">
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img03.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Dra. Mónica</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img04.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Dra. Daniela</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img05.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Dra. Samanta</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img06.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Joseth</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img07.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Dra. Michelle</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img08.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Yoselyn</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img09.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Denia</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario .....
														</p>
													</div>
												</article>
											</div>
											<div class="col-md-6">
												<article class="vertical-item content-padding with_border text-center topmargin_30">
													<div class="item-media">
														<img src="~/fluffypaw/images/FV_img10.jpg" alt="">
														<div class="media-links">
															<a href="blog-single-full.html" class="abs-link"></a>
														</div>
													</div>
													<div class="item-content">
														<span class="date small-text type2 highlight">

														</span>
														<h4 class="entry-title semibold">
															<a href="blog-single-full.html">Dr. Salmerón</a>
														</h4>
														<hr class="divider_1_170">
														<p>
															Médico veterinario con énfasis en Ortopedia, Traumatología y Neurocirugía, quien estará atendiendo todos los días en nuestra clínica.
														</p>
													</div>
												</article>
											</div>

										</div>

									</article>


									<!-- #respond -->
									<!-- #comments -->
								</div>

							</div>



						</div>
						<!--eof .col-sm-8 (main content)-->

					</div>
				</div>
			</section>
		</div>
		<!-- eof #box_wrapper -->
	</div>
	<!-- eof #canvas -->

	<script src="~/fluffypaw/js/compressed.js"></script>
	<script src="~/fluffypaw/js/main.js"></script>
	<script src="~/fluffypaw/js/switcher.js"></script>

</body>