FisioWebFront/Controllers/FAQController.cs
using FisioWebFront.Entities;
using FisioWebFront.Models;
using Microsoft.AspNetCore.Mvc;
using static FisioWebFront.Enum.Enum;

namespace FisioWebFront.Controllers
{
    public class FaqController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        private readonly IConfiguration _config;
        FaqModel modelFaq = new FaqModel();
        public FaqController(IConfiguration config)
        {
            _config = config;
        }

        [HttpGet]
        public ActionResult VerFaq()
        {
            try
            {
                var datos = modelFaq.ConsultarFAQ(_config);
                return View(datos);
            }
            catch (Exception ex)
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult VerListaFaq()
        {
            try
            {
                var datos = modelFaq.ConsultarFAQ(_config);
                return View(datos);
            }
            catch (Exception ex)
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult RegistrarFaq()
        {
            return View();
        }


        [HttpGet]
        public ActionResult EditarFaq(int q)
        {
            try
            {

                var datos = modelFaq.ConsultarFAQ(_config, q);
                return View(datos);
            }
            catch (Exception ex)
            {
                return RedirectToAction("VerListaFaq", "FAQ");
            }
        }


        [HttpGet]
        public ActionResult EliminarFaq(int q)
        {
            try
            {

                var datos = modelFaq.ConsultarFAQ(_config, q);
                return View(datos);
            }
            catch (Exception ex)
            {
                return RedirectToAction("VerListaFaq", "FAQ");
            }
        }

        [HttpPost]
        public ActionResult RegistrarFaq(string pregunta_titulo, string pregunta_respuesta)
        {
            //Registro servicio
            try
            {
                FaqObj FaqInfo = new FaqObj();

                FaqInfo.pregunta_titulo = pregunta_titulo;
                FaqInfo.pregunta_respuesta = pregunta_respuesta;

                modelFaq.RegistrarFAQ(_config, FaqInfo);

                Alert("Registro de FAQ correcto!", NotificationType.success);
                return RedirectToAction("VerListaFaq", "FAQ");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult EditarFaq(FaqObj faq)
        {
            try
            {
                var datos = modelFaq.EditarFAQ(_config, faq);

                Alert("Actualización de datos correcta!", NotificationType.success);
                return RedirectToAction("VerListaFaq", "FAQ");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult BorrarFaq(FaqObj faq)
        {
            try
            {
                var id = faq.id_ayuda;
                var datos = modelFaq.BorrarFAQ(_config, id);

                Alert("Eliminación de FAQ correcto!", NotificationType.success);
                return RedirectToAction("VerListaFaq", "FAQ");
            }
            catch (Exception ex)
            {
                return View();
            }
        }


    }
}

FisioWebFront/Views/FAQ/EditarFaq.cshtml
@model FisioWebFront.Entities.FaqObj
@{
	ViewBag.Title = "EditarFaq";
Layout = "~/Views/Shared/_Layout.cshtml";
}

<html class="no-js">

  <body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
	<![endif]-->

			 <section class="page_breadcrumbs ls ms columns_margin_0">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <ol class="breadcrumb">

                        <li>
                            <a href="index.html">
                                Admin
                            </a>
                        </li>
                        <li>
                            <a href="#"></a>
                        </li>

                        <li class="active">Editar Preguntas y respuestas</li>

                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="ls section_padding_top_65 section_padding_bottom_100">
        <div class="container">
            @using (Html.BeginForm("EditarFaq", "Faq", FormMethod.Post))
            {
                <div class="row">

                    <div class="col-md-8 to_animate" data-animation="scaleAppear">

                        <div class="col-sm-12 to_animate" data-animation="slideRight" data-delay="150">
                            <h3>Editar Servicio</h3>
                        </div>

                        <hr class="divider_1_270 divider_30 left">
                        <h3 class="section_header small bottommargin_30">
                        </h3>

                        @Html.HiddenFor(model => model.id_ayuda)


                        <div class="col-sm-12">
                            <p>
                                Servicio
                            </p>
                            <div class="contact-form-email">


                                @Html.TextAreaFor(model => model.pregunta_titulo, new{
                            @class = "form-control", @required = "required",
                            @size="30", @value="", @name="pregunta_titulo",
                            @id="pregunta_titulo",
                            @style="padding: 0px; margin: 0px;text-align: left;",
                            @pattern=@"^[a-zA-Z0-9\S]+$"
                            })


                            </div>
                        </div>

                        <div class="col-sm-12">
                            <p>
                                Descripción del servicio
                            </p>
                            <div class="contact-form-email">

                                @Html.TextAreaFor(model => model.pregunta_respuesta, new{
                                @class = "form-control", @required = "required",
                            @size="30", @value="", @name="pregunta_respuesta",
                            @id="pregunta_respuesta",
                                @style="padding: 0px; margin: 0px;text-align: left;",
                                @pattern=@"^[a-zA-Z0-9\S]+$"
                            })

                            </div>
                        </div>

                        <div class="col-sm-6">

                            <input class="theme_button color2" type="submit" value="Actualizar">

                        </div>
                        
                        
                        <div class="col-sm-12">
                            <input type="button" value="Volver Atrás" class="theme_button color1" onclick="location.href='@Url.Action("VerListaFaq", "Faq")'">

                        </div>
                      
                         </div>

                </div>
            }
        </div>

    </section>

    <script src="~/fluffypaw/js/compressed.js"></script>
    <script src="~/fluffypaw/js/main.js"></script>
    <script src="~/fluffypaw/js/switcher.js"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>


  </body>


    <!-- Mirrored from html.modernwebtemplates.com/fluffypaw/contact.html por HTTrack Website Copier/3.x [XR&CO'2014], Thu, 01 Dec 2022 17:22:08 GMT -->
</html>

FisioWebFront/Views/FAQ/EliminarFaq.cshtml
@model FisioWebFront.Entities.FaqObj
@{
    ViewBag.Title = "EliminarFaq";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html class="no-js">

<body>
    <!--[if lt IE 9]>
        <div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
    <![endif]-->

    <section class="page_breadcrumbs ls ms columns_margin_0">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <ol class="breadcrumb">

                        <li>
                            <a href="index.html">
                                Admin
                            </a>
                        </li>
                        <li>
                            <a href="#"></a>
                        </li>

                        <li class="active">Eliminar pregunta y respuesta</li>

                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="ls section_padding_top_65 section_padding_bottom_100">
        <div class="container">
            @using (Html.BeginForm("BorrarFaq", "Faq", FormMethod.Post))
            {
                <div class="row">

                    <div class="col-md-8 to_animate" data-animation="scaleAppear">

                        <div class="col-sm-12 to_animate" data-animation="slideRight" data-delay="150">
                            <h3>Eliminar Pregunta y respuesta</h3>
                        </div>

                        <hr class="divider_1_270 divider_30 left">
                        <h3 class="section_header small bottommargin_30">
                            ¿Está seguro de eliminar este pregunta y su respuesta?
                        </h3>

                        @Html.HiddenFor(model => model.id_ayuda)


                        <div class="col-sm-12">
                            <p>
                                Servicio
                            </p>
                            <div class="contact-form-email">


                                @Html.TextAreaFor(model => model.pregunta_titulo, new{
                            @class = "form-control", @required = "required",
                            @size="30", @value="", @name="pregunta_titulo",
                            @id="pregunta_titulo",
                            @style="padding: 0px; margin: 0px;text-align: left;",
                            @pattern=@"^[a-zA-Z0-9\S]+$", @disabled="disabled"
                            })


                            </div>
                        </div>

                        <div class="col-sm-12">
                            <p>
                                Descripción del servicio
                            </p>
                            <div class="contact-form-email">

                                @Html.TextAreaFor(model => model.pregunta_respuesta, new{
                            @class = "form-control", @required = "required",
                            @size="30", @value="", @name="pregunta_respuesta",
                            @id="pregunta_respuesta",
                            @style="padding: 0px; margin: 0px;text-align: left;",
                            @pattern=@"^[a-zA-Z0-9\S]+$", @disabled="disabled"
                            })

                            </div>
                        </div>

                        <div class="col-sm-6">

                            <input class="theme_button color2" type="submit" value="Aceptar">

                        </div>


                        <div class="col-sm-12">
                            <input type="button" value="Cancelar" class="theme_button color1" onclick="location.href='@Url.Action("VerListaFaq", "Faq")'">

                        </div>

                    </div>

                </div>
            }
        </div>

    </section>

    <script src="~/fluffypaw/js/compressed.js"></script>
    <script src="~/fluffypaw/js/main.js"></script>
    <script src="~/fluffypaw/js/switcher.js"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>


</body>


<!-- Mirrored from html.modernwebtemplates.com/fluffypaw/contact.html por HTTrack Website Copier/3.x [XR&CO'2014], Thu, 01 Dec 2022 17:22:08 GMT -->
</html>

FisioWebFront/Views/FAQ/RegistrarFaq.cshtml
@model FisioWebFront.Entities.FaqObj
@{
	ViewBag.Title = "RegistrarFaq";
Layout = "~/Views/Shared/_Layout.cshtml";
}

<html class="no-js">

  <body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
	<![endif]-->

			<section class="page_breadcrumbs ls ms columns_margin_0">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 ">
							<ol class="breadcrumb">
	
									<li>
										<a href="index.html">
											Inicio
										</a>
									</li>
									<li>
										<a href="#">Mi Cuenta</a>
									</li>

									<li class="active">Registrar Pregunta y respuesta</li>
							
							</ol>
						</div>
					</div>
				</div>
			</section>
			<section class="ls section_padding_top_65 section_padding_bottom_100">
				<div class="container">
			@using (Html.BeginForm("RegistrarFaq", "Faq", FormMethod.Post))
					{
					<div class="row">

						<div class="col-md-8 to_animate" data-animation="scaleAppear">

							<div class="col-sm-12 to_animate" data-animation="slideRight" data-delay="150">
								<h3>Registro</h3>
							</div>


							<form class="contact-form row columns_padding_5" method="post" action="https://html.modernwebtemplates.com/">


								<hr class="divider_1_270 divider_30 left">

								<h3 class="section_header small bottommargin_30">
									Registrar pregunta y respuesta

								</h3>

								<div class="col-sm-6">
									<p>
										Pregunta
									</p>
									<div class="contact-form-email">

									<textarea type="text" aria-required="true" size="30" value=""
									   name="pregunta_titulo" id="pregunta_titulo" class="form-control"
									   placeholder="Título de la pregunta" pattern="^[a-zA-Z]+$" required>   </textarea>
									</div>
								</div>

								<div class="col-sm-6">
									<p>
										Respuesta
									</p>
								<div class="contact-form-email">

									<textarea type="text" aria-required="true" size="30" value=""
									   name="pregunta_respuesta" id="pregunta_respuesta" class="form-control"
									   placeholder="Respuesta" pattern="^[a-zA-Z]+$" required>   </textarea>
								</div>
								</div>

	

			

					
							 <div class="col-sm-12">

										<input class="theme_button color1" onsubmit="MostrarAlerta()" on type="submit" value="Registrar pregunta y respuesta">

                                </div>
								      <div class="col-sm-12">
								<input type="button" value="Volver Atras" class="theme_button color1" onclick="location.href='@Url.Action("VerListaFaq", "Faq")'">


                        </div>

							</form>
	

						</div>

					</div>
					 }
				</div>


			</section>


        <script src="~/fluffypaw/js/compressed.js"></script>
        <script src="~/fluffypaw/js/main.js"></script>
        <script src="~/fluffypaw/js/switcher.js"></script>
		<script src="~/js/sweetalert2.all.min.js"></script>


  </body>


    <!-- Mirrored from html.modernwebtemplates.com/fluffypaw/contact.html por HTTrack Website Copier/3.x [XR&CO'2014], Thu, 01 Dec 2022 17:22:08 GMT -->
</html>

FisioWebFront/Views/FAQ/VerFAQ.cshtml
@model IEnumerable<FisioWebFront.Entities.FaqObj>
@{
    ViewBag.Title = "VerFaq";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
			<section class="page_breadcrumbs ls ms columns_margin_0">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 ">
							<ol class="breadcrumb">
								<li>
									<a href="index.html">
										Inicio
									</a>
								</li>
								<li class="active">Preguntas frecuentes</li>
							</ol>
						</div>
					</div>
				</div>
			</section>


			<section class="ls section_padding_50 columns_padding_25">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 text-center">
							<h2 class="section_header small">
								¿Tienes preguntas? Te tenemos las respuestas!
							</h2>
							<p>
								Esta sección te podría dar una guia de las preguntas más frecuentes que nos llegan a través de los distintos medios que tenemos de contacto pero no dude en agendar una cita si necesita más información y un diagnóstico adecuado
							</p>
						</div>
					</div>

					  @foreach (var item in Model)
                            {
					<div class="row vertical-tabs">
						<div class="col-sm-5">

							<!-- Nav tabs -->
							<ul class="nav" role="tablist">
								<li>
								<a href="#vertical-tab1" role="tab" data-toggle="tab"> @Html.DisplayFor(modelItem => item.pregunta_titulo)</a>
								</li>

							</ul>

						</div>

						<div class="col-sm-7">

							<!-- Tab panes -->
							<div class="tab-content no-border">
								<div class="tab-pane fade in active">
								<h3 class="topmargin_0">@Html.DisplayFor(modelItem => item.pregunta_titulo)</h3>
									<p>
									@Html.DisplayFor(modelItem => item.pregunta_respuesta)
									</p>
								</div>
	
						
							</div>

						</div>


					</div>
			}
				</div>
			</section>


	<script src="~/fluffypaw/js/compressed.js"></script>
	<script src="~/fluffypaw/js/main.js"></script>
	<script src="~/fluffypaw/js/switcher.js"></script>


</body>

FisioWebFront/Views/FAQ/VerListaFaq.cshtml
@model IEnumerable<FisioWebFront.Entities.FaqObj>
@{
    ViewBag.Title = "VerListaFaq";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@section scriptsProyecto{

    @* Scrips para que el table este en Espanol *@

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            $('#ListaFAQ').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.11.5/i18n/es-ES.json"
                }
            });
        });

    </script>
}

    <html>

    <body>

        <section class="page_breadcrumbs ls ms columns_margin_0">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 ">
                        <ol class="breadcrumb">

                            <li>
                                <a href="index.html">
                                    Administrador
                                </a>
                            </li>
                            <li>
                                <a href="#">Opciones</a>
                            </li>

                            <li class="active">Lista de preguntas frecuentes</li>

                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="ls section_padding_top_65 section_padding_bottom_100">
            <div class="container">


                <h2>Preguntas y respuestas registradas</h2>

                <br><br/>
                <input type="button" value="Agregar nueva pregunta y respuesta" class="theme_button color2 aligncenter" onclick="location.href='@Url.Action("RegistrarFaq", "Faq")'">
                <br><br />
                <div class="row">
                    <div class="col-sm-10">
                        <table id="ListaFAQ" class="display" style="text-align:center">
                            <thead>
                                <tr>
                                    <th>Preguntas</th>
                                    <th>Respuestas</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.pregunta_titulo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.pregunta_respuesta)
                                    </td>


                                    <td>
                                        <input type="button" value="Editar" class="theme_button color2" onclick="location.href='@Url.Action("EditarFaq", "Faq", new { q = item.id_ayuda })'">

                                    </td>
                                    <td>
                                        <input type="button" value="Eliminar" class="theme_button color1" onclick="location.href='@Url.Action("EliminarFaq", "Faq", new { q = item.id_ayuda })'">

                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </section>


    <script src="~/fluffypaw/js/compressed.js"></script>
    <script src="~/fluffypaw/js/main.js"></script>
    <script src="~/fluffypaw/js/switcher.js"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>



</body>


<!-- Mirrored from html.modernwebtemplates.com/fluffypaw/contact.html por HTTrack Website Copier/3.x [XR&CO'2014], Thu, 01 Dec 2022 17:22:08 GMT -->
</html>